create table user (
  id int unsigned not null auto_increment primary key ,
  username varchar(100) not null default '' comment 'username',
  password char(32) not null default '' comment 'pwd',
  phone_number char(11) not null default '' comment '',
  email varchar(30) not null default '' comment '',
  name varchar(200) not null default '' comment '名字',
  nick_name varchar(30) not null default '' comment '昵称',
  avatar varchar(200) not null default '' comment '头像',
  state tinyint not null default 0 comment '状态,1-启用，2-禁用',
  role_ids varchar(255) not null default '' comment '用户角色 id 用,分割' ,
  dept_id int unsigned not null default 0 comment '部门id',
  created_id int unsigned not null default 0 comment '',
  updated_id int unsigned not null default 0 comment '',
  created_at timestamp not null default current_timestamp comment '创建时间',
  updated_at timestamp not null default current_timestamp on update current_timestamp comment '编辑时间',
  unique key `idx_username` (username),
  unique key `uk_phone_number` (`phone_number`)
) engine = innodb comment 'USER';


alter table user add column `job` varchar(100) not null default '' comment '职位' after `dept_id`;
alter table user add column `is_system` tinyint unsigned not null default 0 comment '是否系统账号' after `job`;




INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('项目概览', 'home', '/workplace', '/dashboard/workplace/index', '', '', 'icon-dashboard', '', '', 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 3, 3, '2024-08-08 08:36:33', '2024-08-08 08:36:33');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('项目管理', 'project', '/project', 'LAYOUT', '/project/project', '', 'icon-menu-unfold', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 3, 3, '2024-08-08 08:37:50', '2024-08-16 11:24:16');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('项目列表', 'project', 'project', '/project/project/index', '', '', 'icon-sort', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 5, 3, 3, '2024-08-08 08:39:22', '2024-08-16 11:57:19');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('添加项目', 'addproject', 'addproject', '/project/addproject/index', '', '', 'icon-plus', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 5, 3, 3, '2024-08-08 08:41:03', '2024-08-08 08:41:03');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('项目详情', 'detail', 'detail', '/project/detail/index', '', '', 'icon-bookmark', '', '', 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 2, 5, 3, 3, '2024-08-08 08:42:42', '2024-08-08 08:46:44');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('项目进度', 'project_ing', '/project', 'LAYOUT', '/project/project_ing', '', 'icon-schedule', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 3, 3, '2024-08-08 08:51:51', '2024-08-16 11:24:16');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('进度列表', 'project_ing', 'project_ing', '/project/project_ing/index', '', '', 'icon-mind-mapping', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 11, 3, 3, '2024-08-08 08:52:42', '2024-08-09 05:11:42');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('系统管理', 'system', '/system', 'LAYOUT', '/system/account', '', 'icon-settings', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 3, 1, '2024-08-16 12:00:04', '2024-08-16 12:04:23');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('用户管理', 'account', 'account', '/system/account/index', '', '', 'icon-user-group', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 13, 3, 3, '2024-08-16 12:01:39', '2024-08-16 12:01:59');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('权限管理', 'rule', '/rule', '/system/rule/index', '', '', 'icon-book', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 13, 3, 1, '2024-08-16 12:03:16', '2024-08-16 12:03:40');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('角色管理', 'role', 'role', '/system/role/index', '', '', 'icon-highlight', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 13, 1, 1, '2024-08-16 12:05:27', '2024-08-16 12:05:36');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('部门管理', 'dept', 'dept', '/system/dept/index', '', '', 'icon-code-square', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 13, 1, 1, '2024-08-16 12:06:15', '2024-08-16 12:06:49');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('节点管理', 'node', '/system/node', '/system/node/index', '', '', 'icon-share-alt', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, '2024-08-16 12:10:49', '2024-08-16 12:10:49');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('用户中心', 'user', '/user', 'LAYOUT', '/user/info', '', '', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, '2024-08-16 12:12:20', '2024-08-16 12:17:24');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('我的项目', 'info', 'info', '/user/info/index', '', '', '', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 19, 1, 1, '2024-08-16 12:13:29', '2024-08-16 12:13:35');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('周报日报', 'weekday', 'weekday', '/user/weekday/index', '', '', '', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 19, 1, 1, '2024-08-16 12:14:03', '2024-08-16 12:14:10');
INSERT INTO rule (title, route_name, route_path, component, redirect, locale, icon, permission, spacer, hide_in_menu, is_ext, no_affix, keepalive, requires_auth, only_page, active_menu, hide_children_in_menu, status, `order`, type, pid, created_id, updated_id, created_at, updated_at) VALUES ('个人设置', 'setting', 'setting', '/user/setting/index', '', '', '', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 19, 1, 1, '2024-08-16 12:14:40', '2024-08-16 12:15:30');
